Repository YAPP-Github/21st-ALL-Rounder-Team-2-BE, pull requests merged in 2023-05, with the labels that each got.

#134 이미 대표 작품으로 설정되어 있는 작품에 대해 대표 작품 등록을 요청할 경우, 대표 설정이 해제되는 버그 해결
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
Labels: 버그

#135 Release 0.2.7
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateController.java
  src/main/java/com/yapp/artie/domain/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/GetUserJoinDateQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/GetUserJoinDateResponse.java
  src/main/java/com/yapp/artie/domain/user/application/port/out/LoadUserPort.java
  src/main/java/com/yapp/artie/domain/user/application/service/GetUserJoinDateService.java
  src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/out/persistence/UserPersistenceAdapterTest.java
  src/test/java/com/yapp/artie/domain/user/application/service/GetUserJoinDateServiceTest.java
Labels: 배포

#138 인가 대상 변경
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/s3/controller/S3Controller.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserThumbnailController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/RenameUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/UserWithdrawalController.java
  src/main/java/com/yapp/artie/global/config/SecurityConfig.java
Labels: 기능 수정

#139 카테고리 순서 변경 불가 버그 수정
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
Labels: 버그

#142 Release 0.2.8
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/s3/controller/S3Controller.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserThumbnailController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/RenameUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/UserWithdrawalController.java
  src/main/java/com/yapp/artie/global/config/SecurityConfig.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
Labels: 배포

#146 테스트용 토큰 발급 로직 수정 및 회원 도메인 패키지 정리
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetTestUserTokenController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserThumbnailController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/RegisterUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/RenameUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/UserWithdrawalController.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/GetUserThumbnailQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/RegisterUserUseCase.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/command/RegisterUserUseCase.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/command/RenameUserUseCase.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/command/UserWithdrawalUseCase.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/query/GetTestUserTokenQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/query/GetUserDetailsQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/query/GetUserJoinDateQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/query/GetUserQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/query/GetUserThumbnailQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/response/GetTestUserTokenResponse.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/response/GetUserJoinDateResponse.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/response/GetUserThumbnailResponse.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/response/RegisterUserResponse.java
  src/main/java/com/yapp/artie/domain/user/application/service/GetTestUserTokenService.java
  src/main/java/com/yapp/artie/domain/user/application/service/GetUserDetailsService.java
  src/main/java/com/yapp/artie/domain/user/application/service/GetUserJoinDateService.java
  src/main/java/com/yapp/artie/domain/user/application/service/GetUserService.java
  src/main/java/com/yapp/artie/domain/user/application/service/GetUserThumbnailService.java
  src/main/java/com/yapp/artie/domain/user/application/service/RegisterUserService.java
  src/main/java/com/yapp/artie/domain/user/application/service/RenameUserService.java
  src/main/java/com/yapp/artie/domain/user/application/service/UserAlreadyExistException.java
  src/main/java/com/yapp/artie/domain/user/application/service/UserWithdrawalService.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetTestUserTokenControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetUserControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetUserThumbnailControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/RegisterUserControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/RenameUserControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/UserWithdrawalControllerTest.java
  src/test/java/com/yapp/artie/domain/user/application/service/GetUserThumbnailServiceTest.java
  src/test/java/com/yapp/artie/domain/user/application/service/RegisterUserServiceTest.java
Labels: 유지 보수, 기능 수정

#148 프리 플라이트 요청 인가 해제
  src/main/java/com/yapp/artie/global/config/SecurityConfig.java
Labels: 버그
