Repository YAPP-Github/21st-ALL-Rounder-Team-2-BE, pull requests merged in 2023-02, with the labels that each got.

#43 캘린더 월별 작품 조회 기능 구현
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/ArtworkContents.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/NullArtwork.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalendarExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalendarExhibitResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/global/util/DateUtils.java
  src/test/java/com/yapp/artie/DateUtilTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 기능 구현

#46 prod 서버의 ddl-auto옵션을 none로 변경
  .github/workflows/deploy-prod.yml
  src/main/resources/application-prod.yml
Labels: 버그, 기능 수정

#47 prod 서버의 ddl-auto옵션을 none로 변경
  src/main/resources/application-prod.yml
Labels: 버그, 기능 수정

#50 대표 작품 설정 API 개발, 작품 수정 API 기타 수정
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/Artwork.java
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
Labels: 기능 구현, 기능 수정

#51 홈 화면 전시 페이징 기능에서 메인 작품의 사진 데이터 포함하도록 개선
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
Labels: 기능 구현, 기능 수정

#54 월별 대표 작품 조회 API 개선, DB 타임존 변경
  docker/docker-compose.yml
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/ArtworkContents.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/NullArtwork.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalendarExhibitResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalenderQueryResultDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/global/util/S3Utils.java
Labels: 기능 구현, 기능 수정

#56 기본 카테고리 로직 제거
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/exception/ChangeDefaultCategoryException.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 기능 구현, 기능 수정

#60 인가 비활성화
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/s3/controller/S3Controller.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/global/config/SecurityConfig.java
Labels: 유지 보수

#61 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/exception/ChangeDefaultCategoryException.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/s3/controller/S3Controller.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/global/config/SecurityConfig.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 배포

#63 Feature/62
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
Labels: 문서화, 기능 수정

#64 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
Labels: 배포

#66 Swagger에서 Page객체에 담겨 반환됨을 정상적으로 명시
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfoPage.java
Labels: 버그

#67 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfoPage.java
Labels: 배포

#68 카테고리 순서 변경 테스트
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
Labels: 버그, 테스트

#71 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 배포

#75 전시 카테고리 수정 기능 구현
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/UpdateExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 기능 구현, 기능 수정

#76 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/UpdateExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 배포

#83 카테고리 순서 변경 버그
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
Labels: 버그, 기능 수정

#84 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
Labels: 배포

#88 캘린더 페이지 내 일자별 전시 목록 조회 API 수정, 특정 날짜 전시 목록 조회 API 추가 및 기타 버그 수정
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalendarExhibitResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalenderQueryResultDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/ExhibitByDateResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/global/util/DateUtils.java
  src/main/resources/application-develop.yml
  src/test/java/com/yapp/artie/DateUtilTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 버그, 기능 구현, 기능 수정

#89 메인 브랜치에 개발용 브랜치 반영
  README.md
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/PinType.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalendarExhibitResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalenderQueryResultDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/ExhibitByDateResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostInfoByCategoryDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostInfoByCategoryDtoPage.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/global/util/DateUtils.java
  src/main/resources/application-develop.yml
  src/test/java/com/yapp/artie/DateUtilTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
  src/test/resources/application.yml
Labels: 배포

#90 마이 페이지 공지사항 기능 구현
  src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CategoryDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/notice/controller/NoticeController.java
  src/main/java/com/yapp/artie/domain/notice/domain/Notice.java
  src/main/java/com/yapp/artie/domain/notice/dto/NoticeDetailInfo.java
  src/main/java/com/yapp/artie/domain/notice/dto/NoticeDto.java
  src/main/java/com/yapp/artie/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/com/yapp/artie/domain/notice/repository/NoticeRepository.java
  src/main/java/com/yapp/artie/domain/notice/service/NoticeService.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/dto/response/UserThumbnailResponseDto.java
  src/main/java/com/yapp/artie/domain/user/service/UserThumbnailService.java
  src/main/java/com/yapp/artie/global/config/swagger/SwaggerConfig.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
  src/test/java/com/yapp/artie/domain/notice/service/NoticeServiceTest.java
  src/test/java/com/yapp/artie/domain/user/service/UserThumbnailServiceTest.java
Labels: 기능 구현

#91 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CategoryDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/notice/controller/NoticeController.java
  src/main/java/com/yapp/artie/domain/notice/domain/Notice.java
  src/main/java/com/yapp/artie/domain/notice/dto/NoticeDetailInfo.java
  src/main/java/com/yapp/artie/domain/notice/dto/NoticeDto.java
  src/main/java/com/yapp/artie/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/com/yapp/artie/domain/notice/repository/NoticeRepository.java
  src/main/java/com/yapp/artie/domain/notice/service/NoticeService.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/dto/response/UserThumbnailResponseDto.java
  src/main/java/com/yapp/artie/domain/user/service/UserThumbnailService.java
  src/main/java/com/yapp/artie/global/config/swagger/SwaggerConfig.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
  src/test/java/com/yapp/artie/domain/notice/service/NoticeServiceTest.java
  src/test/java/com/yapp/artie/domain/user/service/UserThumbnailServiceTest.java
Labels: 기능 구현

#92 첫번째 작품 등록시, 미완성 상태 해제 ( isPublished = true )
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/CreateArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
Labels: 기능 수정

#93 전시 정보에 링크 정보 반영
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CreateExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfo.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostInfoDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/UpdateExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
  src/test/java/com/yapp/artie/domain/user/service/UserThumbnailServiceTest.java
Labels: 기능 수정

#95 공지사항 목록 API 수정
  src/main/java/com/yapp/artie/domain/notice/controller/NoticeController.java
  src/main/java/com/yapp/artie/domain/notice/dto/NoticeDto.java
  src/main/java/com/yapp/artie/domain/notice/repository/NoticeRepository.java
  src/main/java/com/yapp/artie/domain/notice/service/NoticeService.java
  src/test/java/com/yapp/artie/domain/notice/service/NoticeServiceTest.java
Labels: 기능 수정

#97 작품 등록 API의 요청 형태 및 로직 수정 및 Tag 엔티티 변경, 작품 목록 조회 API 버그 개선
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/domain/tag/ArtworkTag.java
  src/main/java/com/yapp/artie/domain/archive/domain/tag/ArtworkTagId.java
  src/main/java/com/yapp/artie/domain/archive/domain/tag/Tag.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/ArtworkInfoDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/UpdateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/ArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/CreateArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/TagDto.java
  src/main/java/com/yapp/artie/domain/archive/exception/TagAlreadyExistException.java
  src/main/java/com/yapp/artie/domain/archive/exception/TagNotFoundException.java
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkTagRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/TagRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkTagService.java
  src/main/java/com/yapp/artie/domain/archive/service/TagService.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
  src/test/resources/application.yml
Labels: 버그, 기능 수정

#98 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/domain/tag/ArtworkTag.java
  src/main/java/com/yapp/artie/domain/archive/domain/tag/ArtworkTagId.java
  src/main/java/com/yapp/artie/domain/archive/domain/tag/Tag.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/ArtworkInfoDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/UpdateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CreateExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfo.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostInfoDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/UpdateExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/ArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/CreateArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/TagDto.java
  src/main/java/com/yapp/artie/domain/archive/exception/TagAlreadyExistException.java
  src/main/java/com/yapp/artie/domain/archive/exception/TagNotFoundException.java
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkTagRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/TagRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkTagService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/archive/service/TagService.java
  src/main/java/com/yapp/artie/domain/notice/controller/NoticeController.java
  src/main/java/com/yapp/artie/domain/notice/dto/NoticeDto.java
  src/main/java/com/yapp/artie/domain/notice/repository/NoticeRepository.java
  src/main/java/com/yapp/artie/domain/notice/service/NoticeService.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
  src/test/java/com/yapp/artie/domain/notice/service/NoticeServiceTest.java
  src/test/java/com/yapp/artie/domain/user/service/UserThumbnailServiceTest.java
  src/test/resources/application.yml
Labels: 배포

#101 마지막 작품 삭제시 해당하는 전시까지 삭제하는 로직 추가
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/Artwork.java
  src/main/java/com/yapp/artie/domain/archive/repository/TagRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 기능 구현, 테스트, 기능 수정

#103 닉네임 변경 API 추가 / 카테고리 목록 조회시 해당 카테고리의 전시 수 필드 반환
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CategoryDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
Labels: 기능 구현

#105 유저 닉네임 변경 API 쿼리 변수 어노테이션 버그 개선
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
Labels: 버그

#106 회원 탈퇴 구현
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/main/java/com/yapp/artie/global/authentication/JwtDecoder.java
  src/main/java/com/yapp/artie/global/authentication/JwtService.java
  src/main/java/com/yapp/artie/global/authentication/JwtServiceImpl.java
  src/main/java/com/yapp/artie/global/authentication/WithdrawalHandler.java
  src/main/java/com/yapp/artie/global/config/SecurityConfig.java
  src/main/java/com/yapp/artie/global/exception/authentication/FirebaseUserNotFoundException.java
  src/main/java/com/yapp/artie/global/exception/authentication/InvalidFirebaseUidException.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
Labels: 기능 구현

#107 작품 삭제 API의 대표 작품 삭제시 타 작품으로 설정되는 로직 추가
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
Labels: 기능 수정

#104 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/Artwork.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CategoryDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/TagRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/main/java/com/yapp/artie/global/authentication/JwtDecoder.java
  src/main/java/com/yapp/artie/global/authentication/JwtService.java
  src/main/java/com/yapp/artie/global/authentication/JwtServiceImpl.java
  src/main/java/com/yapp/artie/global/authentication/WithdrawalHandler.java
  src/main/java/com/yapp/artie/global/config/SecurityConfig.java
  src/main/java/com/yapp/artie/global/exception/authentication/FirebaseUserNotFoundException.java
  src/main/java/com/yapp/artie/global/exception/authentication/InvalidFirebaseUidException.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
  src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
Labels: 배포

#109 유저 탈퇴시 정상적으로 데이터 삭제되지 않는 버그 개선 / 구조 개선 / 테스트 코드 추가 / 일부 authentication 처리 로직 개선
  src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/domain/User.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/BaseIntegrationTest.java
  src/test/java/com/yapp/artie/domain/archive/repository/CategoryRepositoryTest.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/java/com/yapp/artie/domain/user/controller/UserControllerTest.java
  src/test/java/com/yapp/artie/domain/user/domain/UserTest.java
  src/test/java/com/yapp/artie/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
Labels: 버그, 기능 구현, 테스트, 기능 수정

#110 메인 브랜치에 개발용 브랜치 반영
  src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/domain/User.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/BaseIntegrationTest.java
  src/test/java/com/yapp/artie/domain/archive/repository/CategoryRepositoryTest.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/java/com/yapp/artie/domain/user/controller/UserControllerTest.java
  src/test/java/com/yapp/artie/domain/user/domain/UserTest.java
  src/test/java/com/yapp/artie/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
Labels: 배포

#111 서버 아키텍처 추가
  README.md
Labels: 문서화
