Repository YAPP-Github/21st-ALL-Rounder-Team-2-BE, pull requests merged in 2023-04, with the labels that each got.

#123 전시 페이지네이션 카운트 쿼리 수정
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
Labels: 버그

#125 Revert "전시 페이지네이션 카운트 쿼리 수정"
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
Labels: 버그

#128 Notice 도메인 개선
  src/main/java/com/yapp/artie/domain/notice/adapter/in/web/GetNoticeDetailController.java
  src/main/java/com/yapp/artie/domain/notice/adapter/in/web/GetNoticeListController.java
  src/main/java/com/yapp/artie/domain/notice/adapter/out/persistence/NoticePersistenceAdapter.java
  src/main/java/com/yapp/artie/domain/notice/adapter/out/persistence/NoticeRepository.java
  src/main/java/com/yapp/artie/domain/notice/application/port/in/GetNoticeDetailQuery.java
  src/main/java/com/yapp/artie/domain/notice/application/port/in/GetNoticeDetailResponse.java
  src/main/java/com/yapp/artie/domain/notice/application/port/in/GetNoticeListQuery.java
  src/main/java/com/yapp/artie/domain/notice/application/port/out/LoadNoticePort.java
  src/main/java/com/yapp/artie/domain/notice/application/service/GetNoticeDetailService.java
  src/main/java/com/yapp/artie/domain/notice/application/service/GetNoticeListService.java
  src/main/java/com/yapp/artie/domain/notice/controller/NoticeController.java
  src/main/java/com/yapp/artie/domain/notice/domain/Notice.java
  src/main/java/com/yapp/artie/domain/notice/domain/NoticeNotFoundException.java
  src/main/java/com/yapp/artie/domain/notice/dto/NoticeDetailInfo.java
  src/main/java/com/yapp/artie/domain/notice/repository/NoticeRepository.java
  src/main/java/com/yapp/artie/domain/notice/service/NoticeService.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserThumbnailController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/RegisterUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/RenameUserController.java
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/UserWithdrawalController.java
  src/main/java/com/yapp/artie/global/common/annotation/WebAdapter.java
  src/test/java/com/yapp/artie/domain/notice/adapter/in/web/GetNoticeDetailControllerTest.java
  src/test/java/com/yapp/artie/domain/notice/adapter/in/web/GetNoticeListControllerTest.java
  src/test/java/com/yapp/artie/domain/notice/adapter/out/persistence/NoticePersistenceAdapterTest.java
  src/test/java/com/yapp/artie/domain/notice/application/service/GetNoticeDetailServiceTest.java
  src/test/java/com/yapp/artie/domain/notice/application/service/GetNoticeListServiceTest.java
  src/test/java/com/yapp/artie/domain/notice/service/NoticeServiceTest.java
  src/test/resources/com/yapp/artie/domain/notice/adapter/out/persistence/NoticePersistenceAdapterTest.sql
Labels: 유지 보수, 테스트

#129 테스트 유저 토큰 발급 API 추가
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetTestUserTokenController.java
  src/main/java/com/yapp/artie/domain/user/adapter/out/authentication/FirebaseAuthenticationAdapter.java
  src/main/java/com/yapp/artie/domain/user/adapter/out/authentication/FirebaseTokenGenerator.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/GetTestUserTokenQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/GetTestUserTokenResponse.java
  src/main/java/com/yapp/artie/domain/user/application/port/out/GenerateTestTokenPort.java
  src/main/java/com/yapp/artie/domain/user/application/service/GetTestUserTokenService.java
  src/main/java/com/yapp/artie/global/config/SecurityConfig.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetTestUserTokenControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/out/authentication/FirebaseAuthenticationAdapterTest.java
  src/test/java/com/yapp/artie/domain/user/application/service/GetTestUserTokenServiceTest.java
Labels: 기능 구현

#132 유저 조회 API 추가
  src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateController.java
  src/main/java/com/yapp/artie/domain/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/GetUserJoinDateQuery.java
  src/main/java/com/yapp/artie/domain/user/application/port/in/GetUserJoinDateResponse.java
  src/main/java/com/yapp/artie/domain/user/application/port/out/LoadUserPort.java
  src/main/java/com/yapp/artie/domain/user/application/service/GetUserJoinDateService.java
  src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateControllerTest.java
  src/test/java/com/yapp/artie/domain/user/adapter/out/persistence/UserPersistenceAdapterTest.java
  src/test/java/com/yapp/artie/domain/user/application/service/GetUserJoinDateServiceTest.java
Labels: 기능 구현
