Repository YAPP-Github/21st-ALL-Rounder-Team-2-BE, pull requests merged in 2023-01, with the labels that each got.

#10 카테고리 기능 구현
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/Artwork.java
  src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CategoryDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CreateCategoryRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CreateCategoryResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/exception/CategoryAlreadyExistException.java
  src/main/java/com/yapp/artie/domain/archive/exception/CategoryNotFoundException.java
  src/main/java/com/yapp/artie/domain/archive/exception/NotOwnerOfCategoryException.java
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/main/java/com/yapp/artie/global/config/swagger/SwaggerConfig.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
Labels: 기능 구현

#12 전시 기능 구현
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Publication.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CreateExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CreateExhibitResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostInfoDto.java
  src/main/java/com/yapp/artie/domain/archive/exception/ExhibitAlreadyPublishedException.java
  src/main/java/com/yapp/artie/domain/archive/exception/ExhibitNotFoundException.java
  src/main/java/com/yapp/artie/domain/archive/exception/NotOwnerOfExhibitException.java
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/global/config/swagger/SwaggerConfig.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
Labels: 기능 구현

#13 aws 배포 세팅
  .aws/task-definition.json
  .github/workflows/deploy-prod.yml
  Dockerfile
  README.md
  build.gradle
  src/main/resources/application-develop.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 인프라

#15 기존 사용자 등록 시 아이디를 반환
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
Labels: 기능 수정

#18 home 관련 기능 구현과 누락 기능 구현
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Publication.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/UpdateCategoryRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/UpdateExhibitRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
Labels: 기능 구현

#22 작품 등록 및 aws s3, cloudfront 세팅
  .aws/task-definition.json
  .github/workflows/deploy-prod.yml
  README.md
  build.gradle
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/Artwork.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/ArtworkContents.java
  src/main/java/com/yapp/artie/domain/archive/domain/artwork/ExposureCondition.java
  src/main/java/com/yapp/artie/domain/archive/domain/tag/ArtworkTag.java
  src/main/java/com/yapp/artie/domain/archive/domain/tag/Tag.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkResponseDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/ArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/CreateArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/TagDto.java
  src/main/java/com/yapp/artie/domain/archive/exception/TagAlreadyExistException.java
  src/main/java/com/yapp/artie/domain/archive/exception/TagNotFoundException.java
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkTagRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/TagRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkTagService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/archive/service/TagService.java
  src/main/java/com/yapp/artie/global/config/aws/S3Config.java
  src/main/java/com/yapp/artie/global/config/swagger/SwaggerConfig.java
  src/main/java/com/yapp/artie/global/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorResponse.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
Labels: 기능 구현, 인프라, 기능 수정

#20 사용자 홈 화면 상단에 노출될 카테고리 기능 구현
  build.gradle
  src/main/java/com/yapp/artie/domain/archive/controller/CategoryController.java
  src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
  src/main/java/com/yapp/artie/domain/archive/domain/category/HomeCategory.java
  src/main/java/com/yapp/artie/domain/archive/domain/category/HomeCategoryId.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CategoryDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/cateogry/UpdateCategoryRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/exception/ChangeCategoryWrongLengthException.java
  src/main/java/com/yapp/artie/domain/archive/exception/ChangeDefaultCategoryException.java
  src/main/java/com/yapp/artie/domain/archive/exception/ExceededCategoryCountException.java
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/resources/application.yaml
Labels: 기능 구현, 기능 수정

#25 전시 테스트와 리팩터링
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Publication.java
  src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/user/controller/UserController.java
  src/main/java/com/yapp/artie/domain/user/service/UserService.java
  src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
  src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
Labels: 유지 보수, 테스트

#33 전시 상세정보 API, 작품 목록 API 개발 및 일부 Swagger 값 수정
  .github/workflows/deploy-prod.yml
  .gitignore
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/ArtworkThumbnailDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/ArtworkThumbnailDtoPage.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfo.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/CreateArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/s3/controller/S3Controller.java
  src/main/resources/application-aws.yml
Labels: 문서화, 기능 구현

#34 메인 브랜치에 개발용 브랜치 반영
  .github/workflows/deploy-prod.yml
  .gitignore
  src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
  src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
  src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/ArtworkThumbnailDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/ArtworkThumbnailDtoPage.java
  src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
  src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfo.java
  src/main/java/com/yapp/artie/domain/archive/dto/tag/CreateArtworkTagDto.java
  src/main/java/com/yapp/artie/domain/archive/repository/ArtworkRepository.java
  src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
  src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
  src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
  src/main/java/com/yapp/artie/domain/s3/controller/S3Controller.java
  src/main/java/com/yapp/artie/domain/s3/dto/request/GetPresignedUrlRequestDto.java
  src/main/java/com/yapp/artie/domain/s3/dto/response/GetPresignedUrlResponseDto.java
  src/main/java/com/yapp/artie/domain/s3/dto/response/presignedUrlDataDto.java
  src/main/java/com/yapp/artie/domain/s3/service/S3Service.java
  src/main/java/com/yapp/artie/global/config/swagger/SwaggerConfig.java
  src/main/java/com/yapp/artie/global/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
  src/main/java/com/yapp/artie/global/util/S3Utils.java
  src/main/resources/application-aws.yml
Labels: 배포
